"""Fix Models Relation

Revision ID: 8f5111e652b6
Revises: 4af839b16182
Create Date: 2026-01-02 09:26:56.690110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f5111e652b6'
down_revision: Union[str, Sequence[str], None] = '4af839b16182'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie_genres',
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ),
    sa.PrimaryKeyConstraint('movie_id', 'genre_id')
    )
    op.drop_table('genres_movie')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genres_movie',
    sa.Column('movie_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('genre_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], name=op.f('genres_movie_genre_id_fkey')),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], name=op.f('genres_movie_movie_id_fkey')),
    sa.PrimaryKeyConstraint('movie_id', 'genre_id', name=op.f('genres_movie_pkey'))
    )
    op.drop_table('movie_genres')
    # ### end Alembic commands ###
